export const data = {
  boxes: [
    {
      name: "Bathroom Box",
      description: "A monthly box conatining all your bathroom essentials",
      category: "cleaning",
      items: [
        "soap",
        "toliet paper",
        "toothpaste",
        "floss",
        "shampoo",
        "body wash",
      ],
      image: "bathroom.jpg",
    },
    {
      name: "Kitchen Box",
      description: "Get kitchen staples delivered every month",
      category: "food",
      items: ["salt", "pepper", "napkins", "olive oil"],
      image: "kitchen.jpg",
    },
    {
      name: "Laundry Box",
      description: "For all your laundry needs",
      category: "cleaning",
      items: ["detergent", "dryer sheets", "bleach", "softener"],
      image: "laundry.jpg",
    },
    {
      name: "Car Box",
      description: "Keep your car running well and looking great",
      category: "misc",
      items: ["car wipes", "engine oil", "washer fluid"],
      image: "car.jpg",
    },
    {
      name: "Plant Box",
      description: "Spruce up your space with these indoor gardening tools",
      category: "household",
      items: ["plant food", "soil", "seeds"],
      image: "plant.jpg",
    },
    {
      name: "Guitar Box",
      description: "Never miss another practice session",
      category: "hobby",
      items: ["strings", "picks", "cleaning supplies"],
      image: "guitar.jpg",
    },
    {
      name: "Coffee Box",
      description: "Wake up feeling refreshed every day",
      category: "food",
      items: ["beans", "filters", "tools"],
      image: "coffee.jpg",
    },
  ],
  something: "a thing",
};
